### PR TITLE
Translate package from CoffeeScript to ES6

### PR DESCRIPTION
**Pull request by joefitzgerald**
This PR translates all CoffeeScript to ES6, and makes use of the `fbjs` eslint preset.

- [x] file-view.coffee > file-view.js
- [x] get-tags-file.coffee > get-tags-file.js
- [x] go-back-view.coffee > go-back-view.js
- [x] go-to-view.coffee > go-to-view.js
- [x] load-tags-handler.js > load-tags-handjs
- [x] main.coffee > main.js
- [x] project-view.coffee > project-view.js
- [x] symbols-view.coffee > symbols-view.js
- [x] tag-generator.coffee > tag-generator.js
- [x] tag-reader.coffee > tag-reader.js
- [x] symbols-view-spec.coffee > symbols-view-spec.js
- [x] Add `devDependencies` for `eslint` / `fbjs`
- [x] Add .eslintrc.js configuration
- [x] Update package dependencies to latest versions

/cc @zmb3

### Translation Procedure

* Initial setup:
  * `npm install -g decaffeinate`
  * Install `linter-eslint` and enable `--fix` on save
  * Ensure `.eslintrc.js` / `.eslintignore` are configured correctly
* For each file:
  * `decaffeinate <path to the .coffee file`
  * Open `.js` file in atom
  * Save `.js` file
  * Hand edit to remove common issues:
    * Add `'use babel';` at the first line of the file
    * `let` > `const` where possible
    * Comparisons of something with null `if (theThing == null)` become `if (!theThing)`
    * Replace all instances of `guard` / `guardFunc` with plain inline ES6
    * Replace instances of `function () { }` with `() => { }` where appropriate
    * Use carriage return to make single-line statements more readable
    * Remove spurious `return` statements arising from implicit returns in CoffeeScript
  * Delete corresponding `.coffee` file

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
I think we can probably get rid of `BaseSymbolsView`, and have `SymbolsView` inherit directly from `atom-space-pen-views`. Other than that, this looks great. Thanks for the great writeup of your conversion procedure.

**Comment by joefitzgerald** [comment]
:shipit:

**Comment by maxbrunsfeld** [comment]
Thanks @joefitzgerald!

**Pull request merged**
