### PR TITLE
Make quickJumpToSymbol optional

### PR DESCRIPTION
**Pull request by t9md**
I want quick jump is optional.
Its not only because of issue I reported in #105.
Its because I don’t like frequent screen update.
Maybe there are other people like me.

### CODE REVIEW

**Comment by t9md** [comment]
Not sure why Travis test fail. In my local Atom, all spec pass without problem.

**Comment by t9md** [comment]
After quickJump feature introduced to FileView, only inovoking `symbols-view:toggle-file-symbols` move cursor position to first selected symbol's position.
e.g. Go to last line of file then invoking `symbols-view-file-symbols` cause scroll to first symbol.
I don't like this auto scrolling behavior, its not minimalistic, I like screen updated only I `confirmed`.
So please provide configuration option to revert previous FileView's behavior.

**Comment by t9md** [comment]
I still need this feature, just add option to disable auto-jump-selected-symbol.
I want jump to symbol only when I confirm by `enter`.
Don't like auto-scroll to first symbol just opening file-symbol by `cmd-r`.

**Comment by lee-dohm** [comment]
Taking a look.

**Comment by t9md** [comment]
Oh, thanks!

**Comment by lee-dohm** [comment]
Thanks for contrtibuting!

**Comment by t9md** [comment]
Great!! Thanks for taking a look.

**Pull request merged**
