### PR TITLE
Add support for quickly jumping to symbol positions for FileView

### LINKED ISSUE #19: Feature request: Quick focus symbols when selected
I'd like command+r (go to function) to instantly show the function as I highlight it in the list without having to hit enter. If I hit escape, I want it to leave me where I was. This is great for quickly looking at a function definition in the same file without actually navigating there.

### PR DESCRIPTION
**Pull request by brumm**
symbols-view

- only applies to FileView
- takes care of restoring initial position if view does not get confirmed
- fixes #19

### CODE REVIEW

**Comment by brumm** [comment]
Seeing that the other PR is from last November and still open - is participation via PRs welcomed here, or not?

**Comment by kevinsawicki** [comment]
> Seeing that the other PR is from last November and still open - is participation via PRs welcomed here, or not?

Yes, was planning to look at this soon.

**Comment by brumm** [comment]
Awesome, thanks for getting back to me :)

**Comment by kevinsawicki** [comment]
Couple things I noticed after using this for a bit:

The editor scroll position is not restored, only the cursor position is,  makes this case feel odd: canceling the list scrolls to the cursor but does not restore my original editor scroll position. In the gif below, I'm opening the view and then hitting escape, and my window scroll position changes.

scroll-cursor-not-visible

The column position on the line isn't restored. If I open the window and then hit escape, I lose my column position on the line.

column-position

If I have multiple cursors, open the view, then hit escape, I lose all but one of my cursors.

multi-cursor

**Comment by brumm** [comment]
Nice catch, thanks for having a look!

I was looking through atom core and was surprised thats there's no apparent way of serializing cursor/selection state of a TextEditor. Is this correct? I'd rather use the 'official' way of doing this.

**Comment by kevinsawicki** [comment]
> I was looking through atom core and was surprised thats there's no apparent way of serializing cursor/selection state of a TextEditor.

You mean like storing temporarily while the list is showing? I think usually we call `TextEditor::getSelectedBufferRanges` before doing something, and then restore them using `TextEditor::setSelectedBufferRanges`.

**Comment by izuzak** [comment]
Hey @brumm -- sorry for not getting back to you on this! I just noticed that you pushed a new commit, but we don't get notified when that happens if you also don't add a comment. 

It seems that this PR is no longer mergeable due to merge conflicts. Could you update it so that it is mergeable again and ping us when you do so that we can take another look? Thanks!

**Comment by brumm** [comment]
Hey Ivan, thanks for getting back to me! I'll update the code and also add another test for `serializeEditorState` and `deserializeEditorState`

**Comment by brumm** [comment]
Well, there's failing tests that I have no idea how to fix and after three months, I'm very much out of the loop with what happened on master. I'll be closing this and re-implementing the feature on a fresh master.

**Comment by brumm** [comment]
this lives on in #99

**Pull request closed without merging**
