### PR TITLE
Add missing keybindings to the readme

### PR DESCRIPTION
**Pull request by bronson**

### CODE REVIEW

**Comment by izuzak** [comment]
@bronson Thanks for taking the time to update the docs! :heart: Since different OSes have different keybindings, can I talk you into cleaning up the docs a bit more so that it lists the correct keybinding for each command and OS? See [this section](https://github.com/atom/settings-view#commands-and-keybindings) in the Settings View's README for a great example.

**Comment by bronson** [comment]
:+1:

**Comment by bronson** [comment]
Maybe someone can kick Travis?  This PR should be fine.

Or just merging would be even nicer.  :)

**Comment by 50Wliu** [comment]
Any chance you can get rid of the `<br>`s in the table, or does that affect the entire layout?  Other than that, looks good (restarted Travis but it failed again with an unrelated error).

**Comment by bronson** [comment]
The \<br\>s just ensure that you get

     Keybinding
       (OS X)

instead of

    Keybinding (OS
           X)

Happy to delete them if you want.

**Comment by bronson** [comment]
Got rid of them.  With the current table contents, on github, on my browser, it looks like the wrapping isn't an issue anymore.

**Comment by Globegitter** [comment]
:+1:

**Comment by 50Wliu** [comment]
Sorry to ask for yet another change, but can you please change all the keybindings to match Atom's Keybinding Resolver (such as <kbd>Ctrl+r</kbd> to <kbd>ctrl+r</kbd> and <kbd>Ctrl+Shift+r</kbd> to <kbd>ctrl+R</kbd>)?  We've decided to make it consistent with Atom's Keybinding Resolver (and the Settings View README will also be updated to reflect this).
/cc @izuzak @thomasjo

**Comment by bronson** [comment]
"Ctrl+r to ctrl-r" sounds good but "ctrl+shift+r to ctrl-R" sounds dangerous.  I think most people see 'ctrl-r' and 'ctrl-R' as the same keystroke, probably because keyboard keys are almost always upper-case.

Heck, we've had experienced Atom developers get tripped up by the ambiguity: https://github.com/atom/vim-mode/pull/732

You sure you want to make the shift-key implicit?

**Comment by 50Wliu** [comment]
> You sure you want to make the shift-key implicit?

While I personally liked it the way that it was before, I think it's more important to have consistency with the rest of Atom.  It would be nice to create an issue about that regarding how keybindings should be displayed though :).

**Comment by bronson** [comment]
Wait a second, Atom DOES explicitly call out the shift key.

From the Keybindings pane in the Setting tab:

screen shot 2015-07-23 at 7 01 56 pm

@50Wliu do you know where this style consistency is coming from?

**Comment by 50Wliu** [comment]
I must have been mixing up the actual keymaps file and the UI, sorry :grimacing: :disappointed:.  I'll just go change the README right now...

**Pull request merged**
